version: "3"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.prod

  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
